
project_id = "oqzpkqbmcnpxpegshlcm"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lovable.dev"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge-functions]
enabled = true

[functions.weekly-competition-finalizer]
verify_jwt = false

[functions.check-user-availability]
verify_jwt = false

[functions.validate-scoring-integrity]
verify_jwt = false
